name: cac

channels:
- conda-forge
- nvidia

dependencies:
- matplotlib
- python=3.10
- SALib
- setuptools
- scikit-learn
- time
- scikit-image
- pandas
- tensorflow
- keras<3.0.0
- jupyter
- notebook
- jupyterlab
- horovod
- dask
- hpbandster 
- ConfigSpace
- pillow
- cmake
- gfortran
- numpy=1.26.4
- pip
- pip:
  - opencv-python-headless<4.8
  - pathlib
  - meshio==5.3.5
  - bohb-hpo

